### PR TITLE
fix: rename PACKETS.md to packets.md

### PR DESCRIPTION
**Pull request by Armada6**
Only readme, licenses, etc. need to be uppercase, all other markdown docs are fine to be lowercase, and that style is preferred as standard

### CODE REVIEW

**Comment by StealthHydra179** [comment]
hmmmm @nobody5050 
what do you say?

**Comment by vcokltfre** [comment]
I second Armada6's change, conventionally only the readme and license need to be uppercase

**Comment by StealthHydra179** [comment]
aight ok @nobody5050 merge please

**Comment by nobody5050** [comment]
Yeah this all looks good

**Pull request merged**
