### PR TITLE
Create packets.md and initialize first contents 

### PR DESCRIPTION
**Pull request by StealthHydra179**
just started smth, im prbly gonna slowly work on this

### CODE REVIEW

**Comment by StealthHydra179** [comment]
makes it easier in the future, also its just all in one place, and i kinda want to do this

**Comment by nobody5050** [comment]
alright, as long as you don’t modify any code I can merge when you’re ready.

**Comment by StealthHydra179** [comment]
i wont uh il make more pull requests as i go along i guess u can merge rn

**Comment by StealthHydra179** [comment]
(i cant code lmao)

**Comment by StealthHydra179** [comment]
well i can but not in these langs

**Comment by nobody5050** [comment]
You can add whatever changes you want just so long as not modifying the code in this pull.

**Comment by StealthHydra179** [comment]
ye ik, u can merge rn if u want

**Review by nobody5050 — APPROVED** [review]

**Comment by nobody5050** [comment]
Merged and closed

**Comment by nobody5050** [comment]
locked

**Pull request merged**
