### PR TITLE
Finishing Bedrock Packets pt 1 of 2

### PR DESCRIPTION
**Pull request by StealthHydra179**
packets.md

### CODE REVIEW

**Comment by StealthHydra179** [comment]
do not merge

**Comment by nobody5050** [comment]
sure

**Comment by ghost** [comment]
Hey I noticed you guys haven’t been working on MCBES in a while. When will it be continued?

**Comment by nobody5050** [comment]
Whenever it gets done. If you want to work on it feel free to open your own pull with changes, and I’d be happy to help you get started

**Comment by nobody5050** [comment]
Stale pull, closing

**Pull request closed without merging**
