### PR TITLE
Update packets.md 

### PR DESCRIPTION
**Pull request by StealthHydra179**
More stuff and some new sections

### CODE REVIEW

**Comment by StealthHydra179** [comment]
DO NOT MERGE

**Comment by nobody5050** [comment]
ok, lmk when you want merge

**Comment by nobody5050** [comment]
When should we merge?

**Comment by StealthHydra179** [comment]
not yet maybe merge in a day or 2 im rlly busy rn when i get some time ill finish this part up

**Comment by nobody5050** [comment]
alrighty

**Comment by StealthHydra179** [comment]
you know what merge it rn il open a new one later

**Comment by nobody5050** [comment]
Merged

**Comment by StealthHydra179** [comment]
k

**Pull request merged**
